version: "3"
services:
  web:
    container_name: app_web
    build: ./app_gestion
    ports:
      - 5000:5000
    environment:
       FLASK_DEBUG: 0  
    volumes:
      - ./app_gestion:/app  
    networks:
      - pacs   
  proxy:
    image: jc21/nginx-proxy-manager:latest  
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
    networks:
      - pacs     
  db:
    container_name: mysql
    image: mysql:5.7.35
    ports: ["33065:3306"]
    volumes: ["./Orthanc/OrthancDB:/var/lib/mysql"]

    environment:
            MYSQL_DATABASE: "${DB_MYSQL_NAME}"
            MYSQL_USER: "${DB_MYSQL_USER}"
            MYSQL_PASSWORD: "${DB_MYSQL_USER_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_MYSQL_ROOT_PASSWORD}"
    restart: "always"
    networks:
      - pacs

  pacs:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./Orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./Orthanc/OrthancStorage:/var/lib/orthanc/db/
    environment:
        Database: "${DB_MYSQL_NAME}"
        Username: "${DB_MYSQL_USER}"
        Password: "${DB_MYSQL_USER_PASSWORD}"
        login_user: "${LOGIN_USER}"
        login_password: "${LOGIN_PASSWORD}"

    networks:
      - pacs

  ohif_viewer:
    container_name: ohif
    image: ohif/viewer
    ports:
      - 3000:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./Ohif/nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Ohif/ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./Ohif/logo.png:/usr/share/nginx/html/logo.png:ro
    restart: always
    networks:
      - pacs

networks:
  pacs:
