version: "3"
services:
  db:
    container_name: mysql
    image: mysql:5.7.35
    ports: ["3306:3306"]
    volumes: ["./Orthanc/OrthancDB:/var/lib/mysql"]

    environment:
            MYSQL_DATABASE: "${DB_MYSQL_NAME}"
            MYSQL_USER: "${DB_MYSQL_USER}"
            MYSQL_PASSWORD: "${DB_MYSQL_USER_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_MYSQL_ROOT_PASSWORD}"
    restart: "always"
    networks:
      - pacs

  pacs:
    container_name: orthanc
    image: jodogne/orthanc-plugins
    ports:
      - 8042:8042
      - 4242:4242
    volumes:
      - ./Orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro
      - ./Orthanc/OrthancStorage:/var/lib/orthanc/db/
    restart: always
    networks:
      - pacs

  ohif_viewer:
    container_name: ohif
    image: ohif/viewer
    ports:
      - 3000:80
    environment:
      - APP_CONFIG:/usr/share/nginx/html/app-config.js
    volumes:
      - ./Ohif/nginx_ohif.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Ohif/ohif.js:/usr/share/nginx/html/app-config.js:ro
      - ./Ohif/logo.png:/usr/share/nginx/html/logo.png:ro
    restart: always
    networks:
      - pacs

networks:
  pacs:
